import type { WeaponDefinition, WeaponId } from './types';

const weapon = (definition: WeaponDefinition): Readonly<WeaponDefinition> =>
  Object.freeze(definition);

export const WEAPONS: Readonly<
  Record<WeaponId, Readonly<WeaponDefinition>>
> = Object.freeze({
  pistol: weapon({
    id: 'pistol',
    label: 'Service pistol',
    damage: 24,
    roundsPerSecond: 4,
    magazine: 12,
    reserve: Number.POSITIVE_INFINITY,
    reloadMs: 1_100,
    pellets: 1,
    spreadRadians: 0,
    bloomPerShotRadians: 0,
    maxBloomRadians: 0,
    bloomRecoveryMs: 350,
    projectileSpeed: 900,
    projectileRadius: 4,
    penetration: 1,
    splashRadius: 0,
    knockback: 12,
  }),
  rifle: weapon({
    id: 'rifle',
    label: 'Assault rifle',
    damage: 16,
    roundsPerSecond: 9,
    magazine: 30,
    reserve: 60,
    reloadMs: 1_600,
    pellets: 1,
    spreadRadians: 0.012,
    bloomPerShotRadians: 0.008,
    maxBloomRadians: 0.058,
    bloomRecoveryMs: 350,
    projectileSpeed: 1_050,
    projectileRadius: 4,
    penetration: 1,
    splashRadius: 0,
    knockback: 10,
  }),
  shotgun: weapon({
    id: 'shotgun',
    label: 'Combat shotgun',
    damage: 11,
    roundsPerSecond: 1.15,
    magazine: 8,
    reserve: 16,
    reloadMs: 2_100,
    pellets: 8,
    spreadRadians: 0.24,
    bloomPerShotRadians: 0,
    maxBloomRadians: 0,
    bloomRecoveryMs: 350,
    projectileSpeed: 760,
    projectileRadius: 4,
    penetration: 1,
    splashRadius: 0,
    knockback: 34,
  }),
  plasma: weapon({
    id: 'plasma',
    label: 'Plasma projector',
    damage: 30,
    roundsPerSecond: 3.2,
    magazine: 20,
    reserve: 33,
    reloadMs: 1_800,
    pellets: 1,
    spreadRadians: 0,
    bloomPerShotRadians: 0,
    maxBloomRadians: 0,
    bloomRecoveryMs: 350,
    projectileSpeed: 650,
    projectileRadius: 7,
    penetration: 3,
    splashRadius: 0,
    knockback: 18,
  }),
  rocket: weapon({
    id: 'rocket',
    label: 'Rocket launcher',
    damage: 120,
    roundsPerSecond: 0.65,
    magazine: 1,
    reserve: 3,
    reloadMs: 2_400,
    pellets: 1,
    spreadRadians: 0,
    bloomPerShotRadians: 0,
    maxBloomRadians: 0,
    bloomRecoveryMs: 350,
    projectileSpeed: 460,
    projectileRadius: 9,
    penetration: 1,
    splashRadius: 132,
    knockback: 90,
  }),
});
