import {describe,it,expect,vi} from 'vitest';
import * as T from 'three';
import {readFileSync} from 'node:fs';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {attachPassengerVault,PASSENGER_FAMILIES,buildPassengerVault,loadPassengerSource} from './PassengerVault';
import {authoredRoom} from './AuthoredRooms';
import {AUTHORED_ROOM_TOPOLOGIES,PASSENGER_BLOCKOUT} from '../game/roguelike/authoredRoomTopologies';
function fixture(){const room=new T.Group(),fallback=new T.Group();fallback.name='passenger-equipment-fallback';const material=new T.MeshStandardMaterial();material.name='painted-steel-deck';room.add(fallback,new T.Mesh(new T.BoxGeometry(35,.44,25),material));return {room,fallback};}
function source(){const root=new T.Group(),map=new T.Texture({width:1,height:1}),material=new T.MeshStandardMaterial({map,roughnessMap:map}),geometry=new T.BoxGeometry(.2,.2,.2);for(const family of PASSENGER_FAMILIES){const child=new T.Group();child.name=family;child.position.set(.2,.2,.2);child.add(new T.Mesh(geometry,material));root.add(child);}return root;}
async function parse(file:string){const bytes=readFileSync(`public/assets/passenger-vault/runtime/${file}.glb`),length=bytes.readUInt32LE(12),doc=JSON.parse(bytes.subarray(20,20+length).toString());const loader=new GLTFLoader();loader.register(()=>({name:'cpu-texture-stub',loadTexture:async(index:number)=>{const image=doc.images[doc.textures[index].source],start=28+length+(doc.bufferViews[image.bufferView].byteOffset??0);return new T.Texture({width:bytes.readUInt32BE(start+16),height:bytes.readUInt32BE(start+20)});}}));return (await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;}
function families(root:T.Group){return Object.fromEntries(PASSENGER_FAMILIES.map(f=>[f,root.children.find(c=>c.name===f)!]));}
describe('Passenger whole-room owner',()=>{
 it('counts both passes for transparent double-sided added draws',()=>{const s=source(),fs=families(s),material=(s.children[0].children[0] as T.Mesh).material as T.MeshStandardMaterial;material.transparent=true;material.side=T.DoubleSide;for(let i=1;i<=23;i++){const g=new T.BoxGeometry(.1,.1,.1);g.setAttribute('custom'+i,new T.Float32BufferAttribute(new Array(g.attributes.position.count).fill(0),1));fs['monitor-north'].add(new T.Mesh(g,material));}expect(()=>buildPassengerVault(fs)).toThrow('draw budget');});
 it('loads the bounded real bundle once and reports decoded allocation budgets',async()=>{const s=await parse('equipment'),bytes=readFileSync('public/assets/passenger-vault/runtime/equipment.glb'),fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(bytes)),decoder=vi.spyOn(GLTFLoader.prototype,'parseAsync').mockResolvedValue({scene:s} as never);try{const {room}=fixture(),owner=attachPassengerVault(room,vi.fn());await owner.ready;expect(owner.error).toBeUndefined();expect(owner.state).toBe('ready');expect(fetcher).toHaveBeenCalledTimes(1);expect(decoder).toHaveBeenCalledTimes(1);const built=room.getObjectByName('passenger-vault-equipment')!;expect(built.userData.decodedTextureBytes).toBeLessThanOrEqual(32*1024*1024);console.info('Passenger bundle CPU budgets',JSON.stringify({...built.userData,draws:built.children.length,transferBytes:bytes.length}));owner.dispose();}finally{fetcher.mockRestore();decoder.mockRestore();}});
 it('rejects mipmapped PNG allocation overage before decode',async()=>{const bytes=Buffer.from(readFileSync('public/assets/passenger-vault/runtime/equipment.glb')),length=bytes.readUInt32LE(12),doc=JSON.parse(bytes.subarray(20,20+length).toString());for(const image of doc.images){const start=28+length+(doc.bufferViews[image.bufferView].byteOffset??0);bytes.writeUInt32BE(2048,start+16);bytes.writeUInt32BE(2048,start+20);}const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(bytes)),decoder=vi.spyOn(GLTFLoader.prototype,'parseAsync');try{await expect(loadPassengerSource(new AbortController().signal)).rejects.toThrow('decoded image budget');expect(decoder).not.toHaveBeenCalled();}finally{fetcher.mockRestore();decoder.mockRestore();}});
 it('rejects incomplete family bundles and disposes their shared resources',async()=>{const s=source(),mesh=s.children[0].children[0] as T.Mesh,spy=vi.spyOn(mesh.geometry,'dispose');s.children[0].name='missing';const {room,fallback}=fixture(),owner=attachPassengerVault(room,vi.fn(),async()=>s);await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);expect(spy).toHaveBeenCalledTimes(1);});
 it('isolates replaceable equipment and freezes the relocated console footprint',()=>{const plan={width:1200,height:880,...AUTHORED_ROOM_TOPOLOGIES['passenger-vault']!};const room=authoredRoom('passenger-vault',plan)!;expect(room.getObjectByName('passenger-equipment-fallback')?.parent).toBe(room);const ms=PASSENGER_BLOCKOUT.find(p=>p.id==='MS')!.footprint;expect(Math.min(...ms.map(p=>p.y))).toBeCloseTo(479.35);expect(Math.max(...ms.map(p=>p.x))).toBe(1090);});
 it('replaces all fallback atomically with one decoded bundle and approved budgets',async()=>{const s=await parse('equipment'),built=buildPassengerVault(families(s));expect(built.userData.instances).toBe(25);expect(built.children.length).toBeLessThanOrEqual(48);expect(built.userData.triangles).toBeGreaterThan(10000);expect(built.userData.triangles).toBeLessThanOrEqual(100000);expect(new Set(built.children.map(m=>(m as T.Mesh).material)).size).toBeLessThanOrEqual(8);const {room,fallback}=fixture(),load=vi.fn(async()=>s),owner=attachPassengerVault(room,vi.fn(),load);await owner.ready;expect(owner.state).toBe('ready');expect(load).toHaveBeenCalledTimes(1);expect(fallback.parent).toBeNull();owner.dispose();});
 it('preserves every original family world transform and geometry attribute',async()=>{const bundle=await parse('equipment');bundle.updateMatrixWorld(true);for(const f of PASSENGER_FAMILIES){const original=await parse(f);original.updateMatrixWorld(true);const a:T.Mesh[]=[],b:T.Mesh[]=[];original.traverse(o=>{if(o instanceof T.Mesh)a.push(o);});families(bundle)[f].traverse(o=>{if(o instanceof T.Mesh)b.push(o);});expect(b.length).toBe(a.length);a.forEach((mesh,i)=>{expect(b[i].matrixWorld.elements).toEqual(mesh.matrixWorld.elements);expect(b[i].geometry.index?.array).toEqual(mesh.geometry.index?.array);for(const name of Object.keys(mesh.geometry.attributes))expect(b[i].geometry.attributes[name].array).toEqual(mesh.geometry.attributes[name].array);});}});
 it('batches across families without mutating shared service materials',()=>{const s=source(),material=(s.children[0].children[0] as T.Mesh).material as T.MeshStandardMaterial,built=buildPassengerVault(families(s));expect(built.children.length).toBe(2);expect(new Set(built.children.map(m=>(m as T.Mesh).material)).size).toBe(1);expect(material.polygonOffset).toBe(false);const service=built.children.find(m=>m.userData.passengerServiceFinish) as T.Mesh;expect(service).toBeDefined();service.onBeforeRender(null!,null!,null!,service.geometry,material,null!);expect(material.polygonOffset).toBe(true);service.onAfterRender(null!,null!,null!,service.geometry,material,null!);expect(material.polygonOffset).toBe(false);});
 it('rejects actual triangle, draw, material and mipmapped texture overages',()=>{const s=source(),fs=families(s),mesh=s.children[0].children[0] as T.Mesh;mesh.geometry.setIndex(new Array(300003).fill(0));expect(()=>buildPassengerVault(fs)).toThrow('triangle budget');const m=source(),fm=families(m);for(let i=0;i<9;i++)fm['monitor-north'].add(new T.Mesh(new T.BoxGeometry(.1,.1,.1),new T.MeshStandardMaterial()));expect(()=>buildPassengerVault(fm)).toThrow('material budget');const d=source(),fd=families(d),mat=(d.children[0].children[0] as T.Mesh).material;for(let i=1;i<=49;i++){const g=new T.BoxGeometry(.1,.1,.1);g.setAttribute('custom'+i,new T.Float32BufferAttribute(new Array(g.attributes.position.count).fill(0),1));fd['monitor-north'].add(new T.Mesh(g,mat));}expect(()=>buildPassengerVault(fd)).toThrow('draw budget');const t=source(),tm=(t.children[0].children[0] as T.Mesh).material as T.MeshStandardMaterial;tm.map=new T.Texture({width:2048,height:2048});tm.normalMap=new T.Texture({width:2048,height:2048});expect(()=>buildPassengerVault(families(t))).toThrow('decoded image budget');});
 it('fails closed for missing deck and caps untrusted streams before parsing',async()=>{const {room,fallback}=fixture();room.remove(room.children[1]);const owner=attachPassengerVault(room,vi.fn(),async()=>source());await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(new Uint8Array(16*1024*1024+1)));try{const next=attachPassengerVault(fixture().room,vi.fn());await next.ready;expect(next.state).toBe('fallback');expect(String(next.error)).toContain('byte budget');}finally{fetcher.mockRestore();}});
 it('requests only equipment.glb and rejects definitions before decoding',async()=>{const bytes=readFileSync('public/assets/passenger-vault/runtime/equipment.glb'),length=bytes.readUInt32LE(12),doc=JSON.parse(bytes.subarray(20,20+length).toString());doc.materials.push(doc.materials[0]);const json=Buffer.from(JSON.stringify(doc));const padded=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]),body=Buffer.concat([bytes.subarray(0,12),Buffer.alloc(8),padded,bytes.subarray(20+length)]);body.writeUInt32LE(body.length,8);body.writeUInt32LE(padded.length,12);body.writeUInt32LE(0x4e4f534a,16);const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(body));try{await expect(loadPassengerSource(new AbortController().signal)).rejects.toThrow('material budget');expect(fetcher.mock.calls[0][0]).toContain('/runtime/equipment.glb');}finally{fetcher.mockRestore();}});
 it('retains complete fallback on actual HTTP404',async()=>{const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('',{status:404}));try{const {room,fallback}=fixture(),owner=attachPassengerVault(room,vi.fn());await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);owner.dispose();}finally{fetcher.mockRestore();}});
 it('cancels unresolved decode, settles ready and retires late resources once',async()=>{const {room,fallback}=fixture();let resolve!:(s:T.Group)=>void;const owner=attachPassengerVault(room,vi.fn(),()=>new Promise(r=>resolve=r));owner.dispose();await owner.ready;const s=source(),mesh=s.children[0].children[0] as T.Mesh,spy=vi.spyOn(mesh.geometry,'dispose');resolve(s);await Promise.resolve();await Promise.resolve();expect(owner.state).toBe('disposed');expect(fallback.parent).toBe(room);expect(spy).toHaveBeenCalledTimes(1);});
 it('bounds timeout and reentry without stale ownership',async()=>{vi.useFakeTimers();try{const {room,fallback}=fixture(),owner=attachPassengerVault(room,vi.fn(),()=>new Promise(()=>{}),20);await vi.advanceTimersByTimeAsync(21);await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);const next=attachPassengerVault(room,vi.fn(),async()=>source());await next.ready;expect(next.state).toBe('ready');owner.dispose();expect(next.state).toBe('ready');next.dispose();}finally{vi.useRealTimers();}});
 it('retires shared resources once and isolates observer errors',async()=>{const {room}=fixture(),s=source(),m=s.children[0].children[0] as T.Mesh,mat=m.material as T.MeshStandardMaterial;const spies=[vi.spyOn(m.geometry,'dispose'),vi.spyOn(mat,'dispose'),vi.spyOn(mat.map!,'dispose')];const owner=attachPassengerVault(room,()=>{throw Error('observer');},async()=>s);await owner.ready;expect(owner.state).toBe('ready');expect(owner.notificationError).toBeInstanceOf(Error);owner.dispose();owner.dispose();spies.forEach(s=>expect(s).toHaveBeenCalledTimes(1));});
});
