import {describe,it,expect,vi} from 'vitest';
import * as T from 'three';
import {readFileSync} from 'node:fs';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {attachPassengerVault,PASSENGER_FAMILIES,buildPassengerVault} from './PassengerVault';
function fixture(){const room=new T.Group(),fallback=new T.Group();fallback.name='passenger-equipment-fallback';const material=new T.MeshStandardMaterial();material.name='painted-steel-deck';room.add(fallback,new T.Mesh(new T.BoxGeometry(35,.44,25),material));return {room,fallback};}
function source(){const root=new T.Group(),map=new T.Texture();root.add(new T.Mesh(new T.BoxGeometry(.2,.2,.2),new T.MeshStandardMaterial({map,roughnessMap:map})));root.position.set(.2,.2,.2);return root;}
async function actual(){const result={} as Record<string,T.Group>;for(const family of PASSENGER_FAMILIES){const bytes=readFileSync(`public/assets/passenger-vault/runtime/${family}.glb`);const loader=new GLTFLoader();loader.register(()=>({name:'cpu-texture-stub',loadTexture:async()=>new T.Texture()}));result[family]=(await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;}return result;}
import {authoredRoom} from './AuthoredRooms';
import {AUTHORED_ROOM_TOPOLOGIES,PASSENGER_BLOCKOUT} from '../game/roguelike/authoredRoomTopologies';
describe('Passenger whole-room owner',()=>{
 it('isolates replaceable equipment and freezes the relocated console footprint',()=>{const plan={width:1200,height:880,...AUTHORED_ROOM_TOPOLOGIES['passenger-vault']!};const room=authoredRoom('passenger-vault',plan)!;expect(room.getObjectByName('passenger-equipment-fallback')?.parent).toBe(room);const ms=PASSENGER_BLOCKOUT.find(p=>p.id==='MS')!.footprint;expect(Math.min(...ms.map(p=>p.y))).toBeCloseTo(479.35);expect(Math.max(...ms.map(p=>p.x))).toBe(1090);});
 it('replaces all fallback equipment atomically, batches real seven-family geometry and preserves native placements',async()=>{const sources=await actual(),built=buildPassengerVault(sources);expect(built.userData.instances).toBe(25);expect(built.children.length).toBeLessThan(100);expect(built.userData.triangles).toBeGreaterThan(10000);const {room,fallback}=fixture(),owner=attachPassengerVault(room,vi.fn(),async f=>sources[f]);await owner.ready;expect(owner.state).toBe('ready');expect(fallback.parent).toBeNull();owner.dispose();});
 it('fails closed for missing deck and caps untrusted streams before parsing',async()=>{const {room,fallback}=fixture();room.remove(room.children[1]);const owner=attachPassengerVault(room,vi.fn(),async()=>source());await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(new Uint8Array(1500001)));try{const next=attachPassengerVault(fixture().room,vi.fn());await next.ready;expect(next.state).toBe('fallback');expect(String(next.error)).toContain('byte budget');}finally{fetcher.mockRestore();}});
 it('retains complete fallback on actual HTTP404',async()=>{const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('',{status:404}));try{const {room,fallback}=fixture(),owner=attachPassengerVault(room,vi.fn());await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);owner.dispose();}finally{fetcher.mockRestore();}});
 it('cancels unresolved decode, settles ready and retires late resources once',async()=>{const {room,fallback}=fixture();let resolve!:(s:T.Group)=>void;const owner=attachPassengerVault(room,vi.fn(),()=>new Promise(r=>resolve=r));owner.dispose();await owner.ready;const s=source(),mesh=s.children[0] as T.Mesh,spy=vi.spyOn(mesh.geometry,'dispose');resolve(s);await Promise.resolve();await Promise.resolve();expect(owner.state).toBe('disposed');expect(fallback.parent).toBe(room);expect(spy).toHaveBeenCalledTimes(1);});
 it('bounds timeout and reentry without stale ownership',async()=>{vi.useFakeTimers();try{const {room,fallback}=fixture(),owner=attachPassengerVault(room,vi.fn(),()=>new Promise(()=>{}),20);await vi.advanceTimersByTimeAsync(21);await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);const next=attachPassengerVault(room,vi.fn(),async()=>source());await next.ready;expect(next.state).toBe('ready');owner.dispose();expect(next.state).toBe('ready');next.dispose();}finally{vi.useRealTimers();}});
 it('retires shared resources once and isolates observer errors',async()=>{const {room}=fixture(),s=source(),m=s.children[0] as T.Mesh,mat=m.material as T.MeshStandardMaterial;const spies=[vi.spyOn(m.geometry,'dispose'),vi.spyOn(mat,'dispose'),vi.spyOn(mat.map!,'dispose')];const owner=attachPassengerVault(room,()=>{throw Error('observer');},async()=>s);await owner.ready;expect(owner.state).toBe('ready');expect(owner.notificationError).toBeInstanceOf(Error);owner.dispose();owner.dispose();spies.forEach(s=>expect(s).toHaveBeenCalledTimes(1));});
});
