import {describe,it,expect,vi} from 'vitest';
import * as T from 'three';
import {readFileSync} from 'node:fs';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DepthRenderer} from './DepthRenderer';
import {createAwakeningKit} from './AuthoredRooms';
import {attachRecoveryKit} from './RecoveryKit';
function source(){const s=new T.Group(),map=new T.Texture();s.add(new T.Mesh(new T.BoxGeometry(1,.8,.5),new T.MeshStandardMaterial({map,roughnessMap:map})));s.children[0].position.set(0,.4,-.5);return s;}
function fixture(){const room=new T.Group(),fallback=createAwakeningKit(),bank=new T.Group();bank.name='sealed-chamber-bank';room.add(fallback,bank);room.userData.storyFixtures=[{id:'preserved'}];return {room,fallback,bank};}
describe('recovery kit ownership',()=>{
 it('gates invisible combat for kit alone and releases on either terminal state',()=>{const get=Object.getOwnPropertyDescriptor(DepthRenderer.prototype,'roomLoading')!.get!;for(const state of ['loading','ready','fallback'])expect(get.call({recoveryKit:{state}})).toBe(state==='loading');});
 it('loads actual bundled GLB geometry at shared origin and within all exact reservations',async()=>{const bytes=readFileSync('public/assets/awakening/recovery-kit/room-kit.glb');const loader=new GLTFLoader();loader.register(()=>({name:'geometry-test-only',loadTexture:async()=>new T.Texture()}));const s=(await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;const {room,fallback}=fixture();const owner=attachRecoveryKit(room,vi.fn(),async()=>s);await owner.ready;expect(owner.state).toBe('ready');expect(fallback.parent).toBeNull();let triangles=0;s.traverse(o=>{if(o instanceof T.Mesh)triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});expect(triangles).toBe(29304);owner.dispose();});
 it('retains fallback on invalid GLB decoding',async()=>{const {room,fallback}=fixture();const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('invalid glb'));try{const owner=attachRecoveryKit(room,vi.fn());await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);}finally{fetcher.mockRestore();}});

 it('isolates the fallback for atomic replacement',()=>{expect(createAwakeningKit().name).toBe('awakening-kit');});
 it('keeps the bank and story state, preserves PBR and mounts at native scale only after ready',async()=>{const {room,fallback,bank}=fixture(),s=source(),story=room.userData.storyFixtures;let resolve!:(s:T.Group)=>void;const owner=attachRecoveryKit(room,vi.fn(),()=>new Promise(r=>resolve=r));expect(fallback.parent).toBe(room);resolve(s);await owner.ready;expect(owner.state).toBe('ready');expect(fallback.parent).toBeNull();expect(bank.parent).toBe(room);expect(room.userData.storyFixtures).toBe(story);expect(s.position.toArray()).toEqual([204/32,0,700/32]);expect(s.scale.toArray()).toEqual([1,1,1]);expect(s.rotation.toArray().slice(0,3)).toEqual([0,0,0]);expect((s.children[0] as T.Mesh).material).toBeInstanceOf(T.MeshStandardMaterial);owner.dispose();});
 it('retires shared geometry material and texture exactly once on disposal',async()=>{const {room}=fixture(),s=source(),m=s.children[0] as T.Mesh,material=m.material as T.MeshStandardMaterial;const calls=[vi.spyOn(m.geometry,'dispose'),vi.spyOn(material,'dispose'),vi.spyOn(material.map!,'dispose')];s.add(new T.Mesh(m.geometry,material));const owner=attachRecoveryKit(room,vi.fn(),async()=>s);await owner.ready;owner.dispose();owner.dispose();calls.forEach(c=>expect(c).toHaveBeenCalledTimes(1));expect(s.parent).toBeNull();});
 it('retains fallback independently of bank on HTTP404',async()=>{const {room,fallback,bank}=fixture();const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('',{status:404}));try{const owner=attachRecoveryKit(room,vi.fn());await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);expect(bank.parent).toBe(room);owner.dispose();}finally{fetcher.mockRestore();}});
 it('bounds timeout, retires late decode and permits reentry',async()=>{vi.useFakeTimers();try{const {room,fallback}=fixture();let resolve!:(s:T.Group)=>void;const owner=attachRecoveryKit(room,vi.fn(),()=>new Promise(r=>resolve=r),20);await vi.advanceTimersByTimeAsync(21);await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);const s=source(),spy=vi.spyOn((s.children[0] as T.Mesh).geometry,'dispose');resolve(s);await Promise.resolve();await Promise.resolve();expect(spy).toHaveBeenCalledTimes(1);const next=attachRecoveryKit(room,vi.fn(),async()=>source());await next.ready;expect(next.state).toBe('ready');owner.dispose();expect(next.state).toBe('ready');next.dispose();}finally{vi.useRealTimers();}});
 it('does not mutate departed rooms and disposes a stale result',async()=>{const {room,fallback}=fixture();let resolve!:(s:T.Group)=>void;const changed=vi.fn(),owner=attachRecoveryKit(room,changed,()=>new Promise(r=>resolve=r));owner.dispose();const s=source(),spy=vi.spyOn((s.children[0] as T.Mesh).geometry,'dispose');resolve(s);await owner.ready;expect(fallback.parent).toBe(room);expect(changed).not.toHaveBeenCalled();expect(spy).toHaveBeenCalledTimes(1);});
 it('rejects invalid bounds and keeps fallback',async()=>{const {room,fallback}=fixture(),s=source();s.scale.setScalar(5);const spy=vi.spyOn((s.children[0] as T.Mesh).geometry,'dispose'),owner=attachRecoveryKit(room,vi.fn(),async()=>s);await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);expect(spy).toHaveBeenCalledTimes(1);owner.dispose();expect(spy).toHaveBeenCalledTimes(1);});
 it('settles ready when a disposed owner has an unresolved loader',async()=>{const {room}=fixture();const owner=attachRecoveryKit(room,vi.fn(),()=>new Promise(()=>{}));owner.dispose();await owner.ready;expect(owner.state).toBe('disposed');});
 it('observer exceptions do not roll back successful installation',async()=>{const {room}=fixture();const owner=attachRecoveryKit(room,()=>{throw Error('observer');},async()=>source());await owner.ready;expect(owner.state).toBe('ready');expect(owner.notificationError).toBeInstanceOf(Error);owner.dispose();});
});
