import {describe,it,expect,vi} from 'vitest';
import * as T from 'three';
import {createAwakeningRelease} from './AuthoredRooms';
import {attachReleasedBerth} from './ReleasedBerth';
function source(){const s=new T.Group(),map=new T.Texture();s.add(new T.Mesh(new T.BoxGeometry(2,.8,3),new T.MeshStandardMaterial({map,roughnessMap:map})));s.children[0].position.y=.4;return s;}
function fixture(){const room=new T.Group(),fallback=createAwakeningRelease(),bank=new T.Group();bank.name='sealed-chamber-bank';room.add(fallback,bank);room.userData.storyFixtures=[{id:'preserved'}];return {room,fallback,bank};}
describe('released berth ownership',()=>{
 it('isolates the fallback for atomic replacement',()=>{expect(createAwakeningRelease().name).toBe('awakening-release');});
 it('keeps the bank and story state, preserves PBR and mounts at native scale only after ready',async()=>{const {room,fallback,bank}=fixture(),s=source(),story=room.userData.storyFixtures;let resolve!:(s:T.Group)=>void;const owner=attachReleasedBerth(room,vi.fn(),()=>new Promise(r=>resolve=r));expect(fallback.parent).toBe(room);resolve(s);await owner.ready;expect(owner.state).toBe('ready');expect(fallback.parent).toBeNull();expect(bank.parent).toBe(room);expect(room.userData.storyFixtures).toBe(story);expect(s.position.toArray()).toEqual([135/32,0,440/32]);expect(s.scale.toArray()).toEqual([1,1,1]);expect(s.rotation.toArray().slice(0,3)).toEqual([0,0,0]);expect((s.children[0] as T.Mesh).material).toBeInstanceOf(T.MeshStandardMaterial);owner.dispose();});
 it('retires shared geometry material and texture exactly once on disposal',async()=>{const {room}=fixture(),s=source(),m=s.children[0] as T.Mesh,material=m.material as T.MeshStandardMaterial;const calls=[vi.spyOn(m.geometry,'dispose'),vi.spyOn(material,'dispose'),vi.spyOn(material.map!,'dispose')];s.add(new T.Mesh(m.geometry,material));const owner=attachReleasedBerth(room,vi.fn(),async()=>s);await owner.ready;owner.dispose();owner.dispose();calls.forEach(c=>expect(c).toHaveBeenCalledTimes(1));expect(s.parent).toBeNull();});
 it('retains fallback independently of bank on HTTP404',async()=>{const {room,fallback,bank}=fixture();const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('',{status:404}));try{const owner=attachReleasedBerth(room,vi.fn());await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);expect(bank.parent).toBe(room);owner.dispose();}finally{fetcher.mockRestore();}});
 it('bounds timeout, retires late decode and permits reentry',async()=>{vi.useFakeTimers();try{const {room,fallback}=fixture();let resolve!:(s:T.Group)=>void;const owner=attachReleasedBerth(room,vi.fn(),()=>new Promise(r=>resolve=r),20);await vi.advanceTimersByTimeAsync(21);await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);const s=source(),spy=vi.spyOn((s.children[0] as T.Mesh).geometry,'dispose');resolve(s);await Promise.resolve();await Promise.resolve();expect(spy).toHaveBeenCalledTimes(1);const next=attachReleasedBerth(room,vi.fn(),async()=>source());await next.ready;expect(next.state).toBe('ready');owner.dispose();expect(next.state).toBe('ready');next.dispose();}finally{vi.useRealTimers();}});
 it('does not mutate departed rooms and disposes a stale result',async()=>{const {room,fallback}=fixture();let resolve!:(s:T.Group)=>void;const changed=vi.fn(),owner=attachReleasedBerth(room,changed,()=>new Promise(r=>resolve=r));owner.dispose();const s=source(),spy=vi.spyOn((s.children[0] as T.Mesh).geometry,'dispose');resolve(s);await owner.ready;expect(fallback.parent).toBe(room);expect(changed).not.toHaveBeenCalled();expect(spy).toHaveBeenCalledTimes(1);});
 it('rejects invalid bounds and keeps fallback',async()=>{const {room,fallback}=fixture(),s=source();s.scale.setScalar(5);const spy=vi.spyOn((s.children[0] as T.Mesh).geometry,'dispose'),owner=attachReleasedBerth(room,vi.fn(),async()=>s);await owner.ready;expect(owner.state).toBe('fallback');expect(fallback.parent).toBe(room);expect(spy).toHaveBeenCalledTimes(1);owner.dispose();expect(spy).toHaveBeenCalledTimes(1);});
 it('observer exceptions do not roll back successful installation',async()=>{const {room}=fixture();const owner=attachReleasedBerth(room,()=>{throw Error('observer');},async()=>source());await owner.ready;expect(owner.state).toBe('ready');expect(owner.notificationError).toBeInstanceOf(Error);owner.dispose();});
});
