import {beforeAll,afterEach,describe,it,expect,vi} from 'vitest';
import * as T from 'three';
import {existsSync,readFileSync} from 'node:fs';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DepthRenderer} from './DepthRenderer';
import {MAT} from './meshParts';
import {ROOM_TEMPLATES} from '../game/roguelike/roomTemplates';
let api:typeof import('./ResidentialGalleryEquipment');
const file='public/assets/residential-gallery/residential-gallery-equipment.glb';
async function source(){const b=readFileSync(file);return (await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'')).scene;}
function fixture(){const room=new T.Group(),fallback=new T.Group();fallback.name='residential-gallery-equipment-fallback';fallback.add(new T.Mesh(new T.BoxGeometry(),MAT.steel));room.add(fallback);return {room,fallback};}
function spies(s:T.Group){const resources=new Set<T.BufferGeometry|T.Material>();s.traverse(o=>{if(o instanceof T.Mesh){resources.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])resources.add(m);}});return [...resources].map(r=>vi.spyOn(r,'dispose'));}
afterEach(()=>{vi.restoreAllMocks();vi.useRealTimers();});
describe('Residential Gallery equipment owner',()=>{
 beforeAll(async()=>{expect(existsSync('src/render/ResidentialGalleryEquipment.ts')).toBe(true);api=await import('./ResidentialGalleryEquipment');});
 it('loads the real bounded GLB at identity and atomically retires only fallback',async()=>{const s=await source(),before=s.children.map(c=>c.matrix.clone()),{room,fallback}=fixture(),globalDispose=vi.spyOn(MAT.steel,'dispose'),retired=vi.spyOn((fallback.children[0] as T.Mesh).geometry,'dispose'),changed=vi.fn();const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(readFileSync(file)));const owner=api.attachResidentialGalleryEquipment(room,changed);expect(owner.state).toBe('loading');expect(fallback.parent).toBe(room);await owner.ready;expect(owner.error).toBeUndefined();expect(owner.state).toBe('ready');expect(fetcher).toHaveBeenCalledTimes(1);expect(String(fetcher.mock.calls[0][0])).toContain('assets/residential-gallery/residential-gallery-equipment.glb');const bank=room.getObjectByName('residential-gallery-equipment')!;expect(bank.position.toArray()).toEqual([0,0,0]);expect(bank.scale.toArray()).toEqual([1,1,1]);expect(bank.children.map(c=>c.matrix.elements)).toEqual(before.map(m=>m.elements));expect(bank.userData).toMatchObject({draws:22,triangles:5978,materials:7,vertices:12632,decodedTextureBytes:0});bank.traverse(o=>{if(o instanceof T.Mesh){expect(o.castShadow).toBe(true);expect(o.receiveShadow).toBe(true);}});expect(fallback.parent).toBeNull();expect(retired).toHaveBeenCalledTimes(1);expect(globalDispose).not.toHaveBeenCalled();expect(changed).toHaveBeenCalledTimes(1);owner.dispose();});
 it('uses precise bounds for rotated authored batches and preserves all four frozen reservations',async()=>{expect(ROOM_TEMPLATES['residential-gallery'].obstacles).toEqual([{x:280,y:160,width:240,height:100},{x:280,y:520,width:120,height:200},{x:650,y:270,width:260,height:100},{x:780,y:570,width:140,height:150}]);const s=await source();expect(()=>api.validateResidentialGalleryEquipment(s)).not.toThrow();for(const [i,h] of [1.35,1.1,1.35,1.2].entries())expect(new T.Box3().setFromObject(s.children[i],true).max.y).toBeCloseTo(h,5);});
 it.each(['missing','duplicate','extra','bounds','height','nan','normal','material','texture','triangles','vertices','draws'] as const)('rejects %s without partial fallback replacement and disposes once',async defect=>{const s=await source(),mesh=s.children[0].children.find(o=>o instanceof T.Mesh) as T.Mesh;
  if(defect==='missing')s.children[0].name='missing';if(defect==='duplicate')s.children[1].name=s.children[0].name;if(defect==='extra')s.add(new T.Group());if(defect==='bounds')s.children[0].position.x+=1;if(defect==='height')s.children[0].position.y+=.1;if(defect==='nan')mesh.geometry.attributes.position.setX(0,NaN);if(defect==='normal')mesh.geometry.attributes.normal.setX(0,NaN);if(defect==='material')mesh.material=new T.MeshBasicMaterial();if(defect==='texture')(mesh.material as T.MeshStandardMaterial).map=new T.Texture();if(defect==='triangles')mesh.geometry.setIndex(new Array(24003).fill(0));if(defect==='vertices')mesh.geometry.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(60003),3));if(defect==='draws')for(let i=0;i<25;i++)s.children[0].add(mesh.clone());const disposed=spies(s),{room,fallback}=fixture(),changed=vi.fn(),owner=api.attachResidentialGalleryEquipment(room,changed,async()=>s);await owner.ready;expect(owner.state).toBe('fallback');expect(owner.error).toBeDefined();expect(fallback.parent).toBe(room);expect(changed).not.toHaveBeenCalled();owner.dispose();disposed.forEach(spy=>expect(spy).toHaveBeenCalledTimes(1));});
 it('retains complete fallback on HTTP 404',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('',{status:404}));const {room,fallback}=fixture(),owner=api.attachResidentialGalleryEquipment(room,vi.fn());await owner.ready;expect(owner.state).toBe('fallback');expect(String(owner.error)).toContain('404');expect(fallback.parent).toBe(room);owner.dispose();});
 it.each(['header','stream'])('caps %s bytes before decode',async mode=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(new Uint8Array(512*1024+1),mode==='header'?{headers:{'content-length':String(512*1024+1)}}:undefined));const decode=vi.spyOn(GLTFLoader.prototype,'parseAsync');await expect(api.loadResidentialGallerySource(new AbortController().signal)).rejects.toThrow('byte budget');expect(decode).not.toHaveBeenCalled();});
 it.each(['materials','textures','external','extension','header','scenes','scene-index','duplicate-node','cycle','bad-reference'])('rejects untrusted %s before decode',async defect=>{const b=readFileSync(file),n=b.readUInt32LE(12),doc=JSON.parse(b.subarray(20,20+n).toString());if(defect==='materials')doc.materials.push(doc.materials[0]);if(defect==='textures')doc.textures=[{}];if(defect==='external')doc.buffers[0].uri='https://example.invalid/evil.bin';if(defect==='extension')doc.extensionsRequired=['BAD'];if(defect==='scenes')doc.scenes=Array(100).fill(doc.scenes[0]);if(defect==='scene-index')doc.scene=1;if(defect==='duplicate-node')doc.scenes[0].nodes.push(doc.scenes[0].nodes[0]);if(defect==='cycle')doc.nodes[doc.scenes[0].nodes[0]].children=[doc.scenes[0].nodes[0]];if(defect==='bad-reference')doc.scenes[0].nodes[0]=999;const j=Buffer.from(JSON.stringify(doc)),p=Buffer.concat([j,Buffer.alloc((4-j.length%4)%4,32)]),body=Buffer.concat([b.subarray(0,12),Buffer.alloc(8),p,b.subarray(20+n)]);body.writeUInt32LE(body.length,8);body.writeUInt32LE(p.length,12);body.writeUInt32LE(0x4e4f534a,16);if(defect==='header')body.writeUInt32LE(0,0);vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(body));const decode=vi.spyOn(GLTFLoader.prototype,'parseAsync').mockRejectedValue(Error('decode boundary reached'));await expect(api.loadResidentialGallerySource(new AbortController().signal)).rejects.toThrow();expect(decode).not.toHaveBeenCalled();});
 it.each(['cancel','timeout'])('settles %s, permits reentry and disposes stale decode once',async mode=>{const stale=await source(),next=await source(),disposed=spies(stale);vi.useFakeTimers();let resolve!:(s:T.Group)=>void;let signal!:AbortSignal;const {room,fallback}=fixture(),changed=vi.fn(),owner=api.attachResidentialGalleryEquipment(room,changed,s=>{signal=s;return new Promise(r=>resolve=r);},20);if(mode==='cancel')owner.dispose();else await vi.advanceTimersByTimeAsync(21);await owner.ready;expect(owner.state).toBe(mode==='cancel'?'disposed':'fallback');expect(signal.aborted).toBe(true);expect(fallback.parent).toBe(room);const replacement=api.attachResidentialGalleryEquipment(room,vi.fn(),async()=>next);await replacement.ready;resolve(stale);await Promise.resolve();await Promise.resolve();owner.dispose();expect(replacement.state).toBe('ready');expect(next.parent).toBe(room);expect(changed).not.toHaveBeenCalled();disposed.forEach(spy=>expect(spy).toHaveBeenCalledTimes(1));replacement.dispose();});
 it('retires late real loader decode exactly once',async()=>{const s=await source(),disposed=spies(s);let resolve!:(s:never)=>void;vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(readFileSync(file)));const decode=vi.spyOn(GLTFLoader.prototype,'parseAsync').mockImplementation(()=>new Promise(r=>resolve=r));const {room}=fixture(),owner=api.attachResidentialGalleryEquipment(room,vi.fn());await vi.waitFor(()=>expect(decode).toHaveBeenCalled());owner.dispose();await owner.ready;resolve({scene:s} as never);await vi.waitFor(()=>disposed.forEach(spy=>expect(spy).toHaveBeenCalledTimes(1)));});
 it('deduplicates shared resources and isolates observer failure',async()=>{const s=await source(),disposed=spies(s),{room}=fixture(),owner=api.attachResidentialGalleryEquipment(room,()=>{throw Error('observer');},async()=>s);await owner.ready;expect(owner.state).toBe('ready');expect(owner.notificationError).toBeInstanceOf(Error);owner.dispose();owner.dispose();expect(s.parent).toBeNull();disposed.forEach(spy=>expect(spy).toHaveBeenCalledTimes(1));});
});
describe('Residential renderer wiring',()=>{
 it('freezes through the existing roomLoading getter only while loading',()=>{const get=Object.getOwnPropertyDescriptor(DepthRenderer.prototype,'roomLoading')!.get!;for(const state of ['loading','ready','fallback','disposed'])expect(get.call({residentialGalleryEquipment:{state}})).toBe(state==='loading');});
 it('keeps nested fallback outside the real bakeWorld pass',()=>{const {room,fallback}=fixture(),mesh=fallback.children[0];(DepthRenderer.prototype as any).bakeWorld.call({world:room});expect(fallback.parent).toBe(room);expect(fallback.children).toEqual([mesh]);});
 it('constructs all four nested fallbacks through loadRoom, readies and cancels reentry without GPU',async()=>{
  const renderer:any=Object.create(DepthRenderer.prototype),noop=()=>{},material=new T.MeshStandardMaterial();
  Object.assign(renderer,{world:new T.Group(),scene:new T.Scene(),actors:new Map(),nests:new Map(),corpses:[],pickupMeshes:new Map(),poolMeshes:new Map(),temporaryMaterials:[],muzzle:{intensity:0},contacts:{begin:noop,end:noop},effects:{setWorld:noop,clear:noop},afflictions:{clear:noop},actorPool:{release:noop},surfaces:{theme:noop,shipTheme:noop,uv:noop,wall:material,cover:material},floorMaterial:material,camera:new T.OrthographicCamera(-20,20,11,-11),focus:new T.Vector3(),lighting:{loadRoom:noop}});
  let finish!:(response:Response)=>void;const fetcher=vi.spyOn(globalThis,'fetch').mockImplementation(()=>new Promise(r=>finish=r));const node={id:'rg-test',templateId:'residential-gallery',depth:2,kind:'combat'};
  renderer.loadRoom(node);const first=renderer.residentialGalleryEquipment,oldWorld=renderer.world,fallback=oldWorld.getObjectByName('residential-gallery-equipment-fallback');expect(renderer.roomLoading).toBe(true);expect(fallback.parent).toBe(oldWorld);expect(fallback.children.map((c:T.Object3D)=>c.name)).toEqual([0,1,2,3].map(i=>`residential-gallery-blockout-${i}`));expect(fallback.children.every((c:T.Object3D)=>c.children.length>0)).toBe(true);
  finish(new Response(readFileSync(file)));await first.ready;expect(renderer.roomLoading).toBe(false);expect(first.state).toBe('ready');expect(renderer.shadowsDirty).toBe(true);expect(fallback.parent).toBeNull();const bank=oldWorld.getObjectByName('residential-gallery-equipment'),disposed=spies(bank);
  renderer.loadRoom({...node,id:'rg-reentry'});expect(first.state).toBe('disposed');disposed.forEach(spy=>expect(spy).toHaveBeenCalledTimes(1));expect(renderer.roomLoading).toBe(true);const second=renderer.residentialGalleryEquipment;renderer.loadRoom({id:'other',templateId:'security-lock',depth:3,kind:'combat'});await second.ready;expect(second.state).toBe('disposed');expect(renderer.residentialGalleryEquipment).toBeUndefined();expect(renderer.roomLoading).toBe(false);expect(fetcher).toHaveBeenCalledTimes(2);
 });
 it('wires preparation, room reset, final disposal and post-bake attachment',()=>{const text=readFileSync('src/render/DepthRenderer.ts','utf8');expect(text).toContain('this.residentialGalleryEquipment?.ready');expect(text.match(/this\.residentialGalleryEquipment\?\.dispose\(\)/g)).toHaveLength(2);expect(text).toContain("residentialFallback.add(environmentObstacle('habitation'");expect(text.indexOf('this.residentialGalleryEquipment=attachResidentialGalleryEquipment')).toBeGreaterThan(text.indexOf('this.bakeWorld();'));});
});
