import {describe,it,expect,vi} from 'vitest';
import * as T from 'three';
import {buildSealedBank,attachSealedBank} from './SealedChamberBank';
import {createAwakeningRacks} from './AuthoredRooms';
const source=()=>{const g=new T.Group();const m=new T.MeshStandardMaterial({map:new T.Texture(),roughness:.48});g.add(new T.Mesh(new T.BoxGeometry(1.53,.694,2.58),m));g.children[0].position.y=.352;return g;};
describe('sealed chamber bank',()=>{
 it('shares textured geometry across eight native-scale sealed neighbours',()=>{const s=source(),bank=buildSealedBank(s);const pods=bank.children.filter(o=>o instanceof T.InstancedMesh) as T.InstancedMesh[];expect(pods).toHaveLength(1);expect(pods[0].count).toBe(8);expect(pods[0].material).toBe((s.children[0] as T.Mesh).material);expect(pods[0].geometry.attributes.normal).toBeDefined();expect(pods[0].geometry.attributes.uv).toBeDefined();pods[0].computeBoundingBox();expect(pods[0].boundingBox!.min.y).toBeCloseTo(.5);expect(bank.children.length).toBe(3);expect(pods[0].receiveShadow).toBe(true);});
 it('rejects oversize geometry rather than hiding the fallback',()=>{const s=source();s.scale.setScalar(2);expect(()=>buildSealedBank(s)).toThrow(/fit/);});
 it('retains baseline until success and only replaces rack assembly',async()=>{const room=new T.Group(),racks=createAwakeningRacks(),other=new T.Group();room.add(racks,other);let resolve!:(s:T.Group)=>void;const load=vi.fn(()=>new Promise<T.Group>(r=>resolve=r));const changed=vi.fn();const owner=attachSealedBank(room,changed,load);expect(racks.parent).toBe(room);resolve(source());await owner.ready;expect(racks.parent).toBeNull();expect(other.parent).toBe(room);expect(changed).toHaveBeenCalledTimes(1);expect(room.getObjectByName('sealed-chamber-bank')).toBeDefined();owner.dispose();});
 it('keeps baseline on failure',async()=>{const room=new T.Group(),rack=createAwakeningRacks();room.add(rack);const owner=attachSealedBank(room,vi.fn(),async()=>{throw Error('404');});await owner.ready;expect(rack.parent).toBe(room);expect(owner.state).toBe('fallback');owner.dispose();});
 it('disposes stale decoded resources and cannot mutate a departed room',async()=>{const room=new T.Group(),rack=createAwakeningRacks();room.add(rack);let resolve!:(s:T.Group)=>void;const owner=attachSealedBank(room,vi.fn(),()=>new Promise(r=>resolve=r));owner.dispose();const s=source(),mesh=s.children[0] as T.Mesh,geometry=vi.spyOn(mesh.geometry,'dispose'),material=vi.spyOn(mesh.material as T.Material,'dispose'),texture=vi.spyOn((mesh.material as T.MeshStandardMaterial).map!,'dispose');resolve(s);await owner.ready;expect(rack.parent).toBe(room);expect(geometry).toHaveBeenCalledTimes(1);expect(material).toHaveBeenCalledTimes(1);expect(texture).toHaveBeenCalledTimes(1);});
 it('bounds stalled loading and permits a fresh room entry',async()=>{vi.useFakeTimers();const room=new T.Group();room.add(createAwakeningRacks());const owner=attachSealedBank(room,vi.fn(),()=>new Promise(()=>{}),20);await vi.advanceTimersByTimeAsync(21);await owner.ready;expect(owner.state).toBe('fallback');owner.dispose();const next=attachSealedBank(room,vi.fn(),async()=>source());await next.ready;expect(next.state).toBe('ready');next.dispose();vi.useRealTimers();});
});
