import type {BoonEffect} from './game/roguelike/ElementalRuntime';
import {familyBonuses} from './game/roguelike/builds';
import {CombatSystem,ProjectileHitTracker,calculateSplashDamage,type ProjectileRequest} from './game/combat/CombatSystem';
import {EnemySystem,type EnemyEvent} from './game/enemies/EnemySystem';
import {QueenBossSystem,type QueenBossEvent} from './game/enemies/QueenBossSystem';
import {ENEMIES} from './game/enemies/catalog';
import type {StandardEnemyId} from './game/enemies/types';
import {PickupSystem} from './game/pickups/PickupSystem';
import {EncounterDirector,type EncounterEvent} from './game/waves/EncounterDirector';
import {FacilityNavigation} from './game/world/FacilityNavigation';
import {createExpeditionGeometry,canOccupyExpedition,canTraverseExpedition,hasClearExpeditionShot} from './game/world/expeditionGeometry';
import {rerollExpedition,createExpedition,completeExpeditionRoom,claimExpeditionMutation,claimExpeditionResources,chooseExpeditionRoute,defeatExpedition,restoreExpedition,type Expedition} from './game/roguelike/expedition';
import {progressionFor} from './game/roguelike/progression';
import {generateRun} from './game/roguelike/run';
import {authorizeExpeditionDestruction} from './game/roguelike/expedition';
import {storyRoomFor,SACRIFICE_ENDING} from './game/roguelike/storyRooms';
import {MutationRuntime,type MutationTarget} from './game/roguelike/MutationRuntime';
import {loadCheckpoint,saveCheckpoint,clearCheckpoint,type StorageLike} from './game/roguelike/checkpoints';
import type {MutationId,RunNode} from './game/roguelike/types';
import type {WeaponId} from './game/combat/types';
export type GameEffect={type:'shot'|'hit'|'corpse'|'explosion'|'acid'|'hurt'|'pickup'|'sync-corpse'|'enemy-attack'|'enemy-warning'|'boon';boon?:BoonEffect;elements?:readonly ('ice'|'poison'|'fire')[];x:number;y:number;id?:number;vx?:number;vy?:number;radius?:number;weapon?:WeaponId;family?:StandardEnemyId;angle?:number;targetId?:number;targetX?:number;targetY?:number;durationMs?:number};
export type GameInput={x:number;y:number;fire:boolean;angle:number|null;autoAim:boolean};
export type Bullet={visualMuzzle?:{x:number;y:number;z:number;distance:number};x:number;y:number;life:number;kind:'player'|'grenade'|'hazard';request:ProjectileRequest;tracker:ProjectileHitTracker};
export type Pool={id:number;x:number;y:number;radius:number;life:number;warning:number;damage:number;tick:number};
const IDLE:GameInput={x:0,y:0,fire:false,angle:null,autoAim:false};
export class DepthGame {
 combat=new CombatSystem();boss=new QueenBossSystem();pickups=new PickupSystem(0,(a,b,r)=>canTraverseExpedition(this.geometry,a,b,r));
 expedition:Expedition;node:RunNode;geometry:ReturnType<typeof createExpeditionGeometry>;navigation:FacilityNavigation;enemies:EnemySystem;
 player={x:0,y:0,radius:16,angle:0,moving:false,vx:0,vy:0};bullets:Bullet[]=[];pools:Pool[]=[];
 aimVisible:(x:number,y:number)=>boolean=()=>true;
 status:'menu'|'playing'|'paused'|'reward'|'route'|'dead'|'complete'='menu';kills=0;elapsed=0;roomRevision=0;
 private director:EncounterDirector;private mutations:MutationRuntime;private pending:Array<{type:StandardEnemyId;x:number;y:number;elite:boolean;delay:number;guardian?:boolean;attempts?:number}>=[];private clearRequested=false;private hurtCooldown=0;private broodTimer=5;private broods=0;private emergencyUsed=false;private poolId=0;private suppressSave=false;
 constructor(readonly emit:(e:GameEffect)=>void=()=>{},readonly storage:StorageLike|null=null){
  this.expedition=createExpedition(1729,this.combat.getRunResources());this.node=this.findNode();this.geometry=createExpeditionGeometry(this.node);this.navigation=new FacilityNavigation(this.geometry);this.enemies=this.makeEnemies();this.director=this.makeDirector();this.mutations=this.makeMutations();Object.assign(this.player,this.geometry.playerSpawn);
 }
 private findNode(){return generateRun(this.expedition.run.seed,this.expedition.run.version).nodes.find(n=>n.id===this.expedition.run.currentNodeId)!;}
 private makeDirector(){return new EncounterDirector({seed:this.expedition.run.seed,node:this.node,breachIds:this.geometry.breaches.map(b=>b.id)});}
 private makeEnemies(){return new EnemySystem({balance:progressionFor(this.node),canAttack:(a,b)=>hasClearExpeditionShot(this.geometry,a,b),canMove:c=>canOccupyExpedition(this.geometry,{x:c.toX,y:c.toY},c.radius),route:(e,p)=>this.navigation.waypoint(e,p,1)});}
 private makeMutations(){return new MutationRuntime(this.combat,{player:()=>this.player,targets:()=>this.targets(),damage:(id,n)=>this.damage(id,n),move:(id,x,y)=>this.enemies.moveBy(id,x,y),moveCorpse:(t,x,y)=>{const m=this.moveCorpse(t,x,y);this.emit({type:'sync-corpse',id:t.id,x:m.x,y:m.y});return m;},setSlow:(id,m)=>{if(id>0)this.enemies.setSlow(id,m);},canAffect:(a,b)=>hasClearExpeditionShot(this.geometry,a,b),boonEffect:(boon,x,y,targetX,targetY,radius,durationMs)=>this.emit({type:'boon',boon,x,y,targetX,targetY,radius,durationMs}),effect:(x,y,radius)=>this.emit({type:'explosion',x,y,radius})});}
 get encounterRemaining(){return this.director.snapshot.remaining+this.enemies.activeCount+this.enemies.reservedCount+this.pending.reduce((n,p)=>n+(p.type==='carrier'?4:1),0);}
 get canContinue(){const cp=this.suppressSave?null:loadCheckpoint(this.storage);if(!cp)return false;const c=new CombatSystem();c.setBuild(cp.build);return c.restoreRunResources(cp.resources);}
 newRun(seed=(Date.now()^Math.floor(Math.random()*0xffffffff))>>>0){this.suppressSave=true;clearCheckpoint(this.storage);this.combat=new CombatSystem();this.combat.switchWeapon('shotgun');this.expedition=createExpedition(seed,this.combat.getRunResources());this.kills=0;this.elapsed=0;this.enterRoom(false);this.status='reward';}
 continueRun(){const cp=this.suppressSave?null:loadCheckpoint(this.storage);if(!cp)return false;const c=new CombatSystem();c.setBuild(cp.build);if(!c.restoreRunResources(cp.resources))return false;this.combat=c;this.expedition=restoreExpedition(cp);this.enterRoom(false);this.status=cp.run.phase==='route'?'route':'reward';return true;}
 private enterRoom(start=true){this.storySkipped=false;this.mutations.reset();this.node=this.findNode();this.geometry=createExpeditionGeometry(this.node);this.navigation=new FacilityNavigation(this.geometry);this.enemies=this.makeEnemies();this.boss.reset();this.pickups.reset(this.expedition.run.seed+this.node.depth);this.bullets=[];this.pools=[];this.pending=[];this.clearRequested=false;this.emergencyUsed=false;this.hurtCooldown=0;this.broodTimer=5;this.broods=0;this.mutations=this.makeMutations();this.director=this.makeDirector();this.combat.setBuild(this.expedition.build);this.combat.setWave(this.node.depth+1);Object.assign(this.player,this.geometry.playerSpawn,{angle:0,moving:false,vx:0,vy:0});this.roomRevision++;this.status='playing';if(start){this.combat.replenishReserves();if(familyBonuses(this.expedition.build).recovery)this.combat.restoreArmor(6);this.encounterEvents(this.director.start());}}
 pause(){if(this.status==='playing'){this.status='paused';this.player.moving=false;}}
 resume(){if(this.status==='paused')this.status='playing';}
 menu(){this.status='menu';this.player.moving=false;}
 private save(){const result=saveCheckpoint(this.storage,{version:1,savedAt:Date.now(),...this.expedition});if(result.status==='saved')this.suppressSave=false;}
 chooseMutation(id:MutationId){if(this.status!=='reward')return;this.expedition=claimExpeditionMutation(this.expedition,id);this.combat.setBuild(this.expedition.build);if(this.expedition.run.phase==='combat'){this.enterRoom();return;}this.status='route';this.save();}
 reroll(){if(this.status!=='reward')return false;try{this.expedition=rerollExpedition(this.expedition);this.combat.setCredits(this.expedition.resources.credits);this.save();return true;}catch{return false;}}
 claimResources(purchase:'heal'|'armor'|'ammo'|null=null){
  if(this.status!=='reward'||!['healing','supplies'].includes(this.node.reward))return;
  const costs={heal:100,armor:90,ammo:100},act=progressionFor(this.node).act;
  if(purchase&&this.combat.snapshot.credits<costs[purchase])return;
  if(this.node.reward==='healing'){this.combat.restoreHealth(35+act*5);this.combat.restoreArmor(15+act*5);}
  const pack=(boost=false)=>{const r=this.combat.getRunResources(),ammo={...r.ammo};for(const [id,amount]of Object.entries({rifle:60+act*15,shotgun:18+act*6,plasma:24+act*6,rocket:2})){const key=id as WeaponId;ammo[key]={...ammo[key],reserve:Math.min(100000,ammo[key].reserve+Math.max(1,Math.round(amount*(boost?.65:1)/3)))};}this.combat.restoreRunResources({...r,ammo,grenades:Math.min(6,r.grenades+(boost?0:1))});};
  if(this.node.reward==='supplies')pack();
  if(purchase){this.combat.setCredits(this.combat.snapshot.credits-costs[purchase]);if(purchase==='heal')this.combat.restoreHealth(30);else if(purchase==='armor')this.combat.restoreArmor(25);else pack(true);}
  this.expedition=claimExpeditionResources(this.expedition,this.combat.getRunResources());this.status='route';this.save();
 }
 get boonStatuses(){return(id:number)=>this.mutations.statuses(id);}
 get storyRoom(){return storyRoomFor(this.node.templateId);}
 private storySkipped=false;
 get storyPresentation(){return this.storySkipped?undefined:this.storyRoom?.story;}
 skipStory(){this.storySkipped=true;}
 get storyStatus(){
  if(!this.storyRoom)return '';
  if(this.status==='complete')return SACRIFICE_ENDING;
  const depth=this.node.depth,cleared=this.expedition.run.completedNodeIds.length>depth;
  if(depth>=11)return 'NEW EARTH WARNED / PASSENGERS ALIVE / AI LIED. THE PURGE KILLS EVERYONE. LOCAL RECORD: AI KNEW BEFORE AWAKENING.';
  if(depth>=10)return 'WARNING RECEIVED / NEW EARTH PREPARING FOR WAR / SERVICE DISPLAY: PURGE DESTROYS OCCUPIED CRYO DECKS.';
  if(depth===9&&cleared)return 'WARNING RECEIVED / NEW EARTH PREPARING FOR WAR / PASSENGERS ALIVE';
  return 'MERCENARY / PASSENGERS ALIVE / AI PROMISE: YOU AND THE PASSENGERS WILL SURVIVE.';
 }
 authorizeDestruction(){
  if(this.status!=='route'||this.node.templateId!=='manual-control-chamber')return false;
  this.expedition=authorizeExpeditionDestruction(this.expedition);this.enterRoom();return true;
 }
 private collectLoot(sweep=false){for(const p of this.pickups.snapshot){const c=this.pickups.collect(p.id,sweep?p:this.player);if(!c.collected)continue;const r=c.reward;if(r.kind==='health')this.combat.restoreHealth(r.amount);else if(r.kind==='armor')this.combat.restoreArmor(r.amount);else if(r.kind==='ammo')this.combat.collectAmmoPack();else if(r.kind==='grenade')this.combat.addGrenades(r.amount);else this.combat.setCredits(this.combat.snapshot.credits+r.amount);this.emit({type:'pickup',x:p.x,y:p.y});}}

 route(id:string){if(this.status!=='route'||this.node.templateId==='manual-control-chamber')return;this.expedition=chooseExpeditionRoute(this.expedition,id);this.enterRoom();}
 moveCorpse(p:{x:number;y:number;radius:number},dx:number,dy:number){const solids=p===this.player?this.targets().filter(t=>t.immovable):[];const canMove=(x:number,y:number)=>canOccupyExpedition(this.geometry,{x,y},p.radius)&&(p!==this.player||solids.every(t=>Math.hypot(x-t.x,y-t.y)>=p.radius+t.radius));let x=p.x,y=p.y,blocked=false;const steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/6));for(let i=0;i<steps;i++){if(canMove(x+dx/steps,y))x+=dx/steps;else blocked=true;if(canMove(x,y+dy/steps))y+=dy/steps;else blocked=true;}return{x,y,blocked};}
 private targetCache:MutationTarget[]|null=null;private targetSnapshot:unknown;
 targets():MutationTarget[]{const snapshot=this.enemies.snapshot;if(this.targetCache&&this.targetSnapshot===snapshot)return this.targetCache;this.targetSnapshot=snapshot;const a:MutationTarget[]=snapshot.enemies.map(e=>({id:e.id,x:e.x,y:e.y,radius:e.radius,health:e.health,maxHealth:e.maxHealth}));const q=this.boss.snapshot;if(q.active){a.push({id:-1,x:q.x,y:q.y,radius:92,health:q.health,maxHealth:q.maxHealth,immovable:true});for(const n of q.nests)a.push({id:-100-n.id,x:n.x,y:n.y,radius:28,health:n.health,maxHealth:n.maxHealth,immovable:true});}this.targetCache=a;return a;}
 private spawn(type:StandardEnemyId,x:number,y:number,elite=false,guardian=false){const radius=ENEMIES[type].radius;for(let i=0;i<25;i++){const angle=i*2.399,dist=i?20+Math.sqrt(i)*18:0,p={x:x+Math.cos(angle)*dist,y:y+Math.sin(angle)*dist};if(Math.hypot(p.x-this.player.x,p.y-this.player.y)>radius+this.player.radius+80&&canOccupyExpedition(this.geometry,p,radius)){const result=this.enemies.spawn(type,p.x,p.y,elite);if(result.spawned&&guardian)this.enemies.promote(result.enemy.id,this.node.depth===(this.storyRoom?5:3)?'warden':'matron');return result.spawned;}}return false;}
 private encounterEvents(events:readonly EncounterEvent[]){for(const e of events){if(e.type==='spawn-request'){const chosen=this.geometry.breaches.find(b=>b.id===e.breachId)!;const safe=Math.hypot(chosen.x-this.player.x,chosen.y-this.player.y)>240?chosen:[...this.geometry.breaches].sort((a,b)=>Math.hypot(b.x-this.player.x,b.y-this.player.y)-Math.hypot(a.x-this.player.x,a.y-this.player.y))[0];const x=safe.x+(safe.facing==='east'?56:-56),y=safe.y,guardian=progressionFor(this.node).guardian&&e.spawnId.endsWith('spawn-0');
 this.pending.push({type:guardian&&this.node.depth===(this.storyRoom?15:7)?'carrier':e.enemyId,x,y,elite:e.elite,delay:650,guardian});this.emit({type:'enemy-warning',x,y,radius:38,durationMs:650});}else if(e.type==='boss-start')this.boss.start(this.geometry.bossSpawn.x,this.geometry.bossSpawn.y);else if(e.type==='room-clear'){if(this.node.kind==='boss')this.clearRequested=true;else this.clearRoom();}}}
 private clearRoom(){if(this.combat.snapshot.dead||this.expedition.run.phase!=='combat')return;this.collectLoot(true);this.expedition=completeExpeditionRoom(this.expedition,this.combat.getRunResources());this.bullets=[];this.pools=[];this.pending=[];this.enemies.reset();this.player.moving=false;this.status=this.expedition.run.phase==='complete'?'complete':'reward';if(this.status==='complete'){if(this.storyRoom){this.combat.applyDamage(1000000);this.expedition=Object.freeze({...this.expedition,resources:this.combat.getRunResources()});this.emit({type:'explosion',x:this.player.x,y:this.player.y,radius:900});}clearCheckpoint(this.storage);this.suppressSave=true;}else this.save();}
 private enemyEvents(events:readonly EnemyEvent[]){for(const e of events){if(e.type==='death'){this.kills++;this.combat.setCredits(this.combat.snapshot.credits+e.reward);this.pickups.rollEnemyDrop(e.enemyType,e.x,e.y);this.emit({type:'corpse',id:e.enemyId,x:e.x,y:e.y,vx:e.impulse?.x??0,vy:e.impulse?.y??0,family:e.enemyType});}else if(e.type==='contact-attack'){const attacker=this.enemies.getSnapshot(e.enemyId);if(attacker)this.emit({type:'enemy-attack',id:e.enemyId,family:e.enemyType,x:attacker.x,y:attacker.y,angle:Math.atan2(this.player.y-attacker.y,this.player.x-attacker.x)});this.hurt(e.damage);}else if(e.type==='spawn-request')this.pending.push({type:e.enemyType,x:e.x,y:e.y,elite:e.elite,delay:450});else if(e.type==='attack-warning'){this.emit({type:'enemy-warning',id:e.enemyId,family:e.enemyType,x:e.x,y:e.y,targetX:e.targetX,targetY:e.targetY,durationMs:e.durationMs,radius:32});}else if(e.type==='hazard-attack'){const angle=Math.atan2(e.targetY-e.sourceY,e.targetX-e.sourceX);this.emit({type:'enemy-attack',id:e.enemyId,family:'spitter',x:e.sourceX,y:e.sourceY,angle});this.bullets.push({x:e.sourceX,y:e.sourceY,life:3,kind:'hazard',request:{weaponId:'plasma',damage:e.damage,speed:260,radius:9,angle,penetration:1,splashRadius:0,knockback:0},tracker:new ProjectileHitTracker(1)});}}}
 private queenEvents(events:readonly QueenBossEvent[]){for(const e of events){if(e.type==='minion-spawn-request'&&this.enemies.activeCount+this.pending.length<20)this.pending.push({type:'crawler',x:e.x,y:e.y,elite:false,delay:650});else if(e.type==='area-attack'){this.emit({type:'enemy-attack',id:-1,x:this.boss.snapshot.x,y:this.boss.snapshot.y});this.emit({type:'acid',x:e.x,y:e.y,radius:e.radius});if(Math.hypot(this.player.x-e.x,this.player.y-e.y)<e.radius+16)this.hurt(e.damage);this.pools.push({id:++this.poolId,x:e.x,y:e.y,radius:e.radius*.75,life:2,warning:0,damage:6,tick:.5});}else if(e.type==='nest-destroyed')this.emit({type:'explosion',x:e.x,y:e.y,radius:64});else if(e.type==='queen-defeated'){this.emit({type:'explosion',x:e.x,y:e.y,radius:240});this.encounterEvents(this.director.reportBossDefeated());}}}
 damage(id:number,amount:number,impulse?:{x:number;y:number}){this.targetCache=null;if(id>0){const r=this.enemies.applyDamage(id,amount,impulse);this.enemyEvents(r.events);return{applied:r.applied,died:r.died};}const r=this.boss.applyDamage(id===-1?{type:'queen'}:{type:'nest',id:-100-id},amount);this.queenEvents(r.events);return{applied:r.applied,died:r.destroyed};}
 hurt(amount:number){if(this.status!=='playing'||this.hurtCooldown>0||!Number.isFinite(amount)||amount<=0)return;this.hurtCooldown=.22;const armorBefore=this.combat.snapshot.armor;this.combat.applyDamage(amount);if(!this.combat.snapshot.dead)this.mutations.hurt(armorBefore,this.combat.snapshot.armor,this.player);if(!this.emergencyUsed&&!this.combat.snapshot.dead&&this.combat.snapshot.health<30&&this.combat.build.mutations.includes('emergency-plating')){this.emergencyUsed=true;this.combat.restoreArmor(20);this.emit({type:'boon',boon:'shield',x:this.player.x,y:this.player.y});}this.emit({type:'hurt',x:this.player.x,y:this.player.y});if(this.combat.snapshot.dead){this.expedition=defeatExpedition(this.expedition);this.status='dead';this.player.moving=false;this.director.reportPlayerDefeated();this.bullets=[];this.pools=[];clearCheckpoint(this.storage);this.suppressSave=true;}}
 reload(){if(this.status==='playing')this.combat.startReload();}
 heal(){if(this.status==='playing')this.combat.consumeMedkit();}
 switchWeapon(id:WeaponId){if(this.status==='playing')this.combat.switchWeapon(id);}
 grenade(){if(this.status!=='playing')return;const r=this.combat.throwGrenade(this.player.angle);if(r)this.bullets.push({x:this.player.x,y:this.player.y,life:1.1,kind:'grenade',request:{...r,weaponId:'rocket',radius:7,penetration:1,mutationShotId:this.combat.nextMutationEventId('grenade')},tracker:new ProjectileHitTracker(1)});}
 private blast(b:Bullet){const elements=new Set<'ice'|'poison'|'fire'>();for(const t of this.targets()){if(Math.hypot(t.x-b.x,t.y-b.y)>b.request.splashRadius||!hasClearExpeditionShot(this.geometry,b,t))continue;const s=this.mutations.statuses(t.id);if(s.chilled||s.frozen)elements.add('ice');if(s.poisoned)elements.add('poison');if(s.burning)elements.add('fire');}this.emit({type:'explosion',x:b.x,y:b.y,radius:b.request.splashRadius,elements:[...elements]});const cause={chainId:b.request.mutationShotId??this.combat.nextMutationEventId('blast'),depth:0};for(const t of this.targets()){const distance=Math.hypot(t.x-b.x,t.y-b.y);if(distance>b.request.splashRadius||!hasClearExpeditionShot(this.geometry,b,t))continue;const n=calculateSplashDamage(b.request.damage,distance,b.request.splashRadius);const r=this.damage(t.id,n,{x:(t.x-b.x)/(distance||1)*b.request.knockback,y:(t.y-b.y)/(distance||1)*b.request.knockback});if(r.applied){this.mutations.hit(cause.chainId,b.request.weaponId,t,{x:(t.x-b.x)/(distance||1),y:(t.y-b.y)/(distance||1)},b.request.primed);if(r.died)this.mutations.kill(t,'direct',cause);}}}
 private updateBullets(dt:number){for(const b of [...this.bullets]){if(this.status!=='playing')break;b.life-=dt;const dx=Math.cos(b.request.angle)*b.request.speed*dt,dy=Math.sin(b.request.angle)*b.request.speed*dt;const steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/7));let done=false;for(let i=0;i<steps&&!done;i++){
   const next={x:b.x+dx/steps,y:b.y+dy/steps};if(!canOccupyExpedition(this.geometry,next,b.request.radius)){if(b.kind==='grenade'){b.request={...b.request,speed:0};break;}if(b.request.splashRadius)this.blast(b);else this.emit({type:'hit',x:b.x,y:b.y,angle:b.request.angle,weapon:b.request.weaponId});done=true;break;}b.x=next.x;b.y=next.y;
   if(b.kind==='hazard'){if(Math.hypot(b.x-this.player.x,b.y-this.player.y)<b.request.radius+16){this.emit({type:'acid',x:b.x,y:b.y,angle:b.request.angle});this.hurt(b.request.damage);done=true;}continue;}if(b.kind==='grenade')continue;
   for(const t of this.targets()){if(Math.hypot(b.x-t.x,b.y-t.y)>t.radius+b.request.radius)continue;const hit=b.tracker.hit(t.id);if(!hit.applied)continue;if(b.request.splashRadius){this.blast(b);done=true;break;}const direction={x:Math.cos(b.request.angle),y:Math.sin(b.request.angle)},r=this.damage(t.id,b.request.damage,{x:direction.x*b.request.knockback,y:direction.y*b.request.knockback});this.emit({type:r.applied?'acid':'hit',x:b.x,y:b.y,angle:b.request.angle,weapon:b.request.weaponId,targetId:t.id});const shot=b.request.mutationShotId??this.combat.nextMutationEventId('hit');if(r.applied){this.mutations.hit(shot,b.request.weaponId,t,direction,b.request.primed);if(r.died)this.mutations.kill(t,'direct',{chainId:shot,depth:0});}if(hit.exhausted){done=true;break;}}
  }if(b.life<=0){if(b.kind==='grenade')this.blast(b);done=true;}if(done){const i=this.bullets.indexOf(b);if(i>=0)this.bullets.splice(i,1);}}
 }
 update(deltaMs:number,input:GameInput=IDLE){if(this.status!=='playing')return;const ms=Math.min(50,Math.max(0,deltaMs)),dt=ms/1000;this.elapsed+=dt;this.hurtCooldown=Math.max(0,this.hurtCooldown-dt);const length=Math.max(1,Math.hypot(input.x,input.y));const moved=this.moveCorpse(this.player,input.x/length*220*dt,input.y/length*220*dt);this.player.vx=dt?(moved.x-this.player.x)/dt:0;this.player.vy=dt?(moved.y-this.player.y)/dt:0;this.player.moving=Math.hypot(this.player.vx,this.player.vy)>3;this.player.x=moved.x;this.player.y=moved.y;
  if(input.angle!==null)this.player.angle=input.angle;else if(input.autoAim){const q=this.boss.snapshot,target=this.targets().filter(t=>(t.id!==-1||q.vulnerable)&&this.aimVisible(t.x,t.y)&&Math.hypot(t.x-this.player.x,t.y-this.player.y)<720&&hasClearExpeditionShot(this.geometry,this.player,t)).sort((a,b)=>Math.hypot(a.x-this.player.x,a.y-this.player.y)-Math.hypot(b.x-this.player.x,b.y-this.player.y))[0];if(target)this.player.angle=Math.atan2(target.y-this.player.y,target.x-this.player.x);}
  const reloadBefore=this.combat.snapshot;this.combat.regenerateReserves(ms);this.combat.update(ms,input.fire);if(reloadBefore.reloading&&!this.combat.snapshot.reloading&&this.combat.snapshot.magazine>reloadBefore.magazine)this.mutations.completedReload(this.player);if(input.fire){const shots=this.combat.fire(this.player.angle);if(shots.length){this.emit({type:'shot',x:this.player.x,y:this.player.y,weapon:shots[0].weaponId,angle:this.player.angle});for(const request of shots)this.bullets.push({x:this.player.x,y:this.player.y,life:2,kind:'player',request,tracker:new ProjectileHitTracker(request.penetration)});}}this.combat.reloadIfEmpty();
  this.navigation.prepare(this.player,1);this.enemyEvents(this.enemies.update(ms,this.player));if(this.status!=='playing')return;this.queenEvents(this.boss.update(ms,this.player,this.enemies.activeCount+this.pending.length));this.updateBullets(dt);if(this.status!=='playing')return;this.mutations.update(ms);
  for(const pool of this.pools){pool.life-=dt;pool.tick-=dt;if(pool.tick<=0){pool.tick=.5;if(Math.hypot(pool.x-this.player.x,pool.y-this.player.y)<pool.radius+16)this.hurt(pool.damage);}}this.pools=this.pools.filter(p=>p.life>0);if(this.status!=='playing')return;
  this.pickups.update(ms,this.player,{magnetEnabled:true,magnetRange:familyBonuses(this.combat.build).recovery?144:120});this.collectLoot();
  if(this.node.depth===(this.storyRoom?15:7)&&this.broods<3){const matron=this.enemies.snapshot.enemies.find(e=>e.champion==='matron');if(matron){this.broodTimer-=dt;if(this.broodTimer<=0&&this.enemies.activeCount+this.enemies.reservedCount+this.pending.reduce((n,p)=>n+(p.type==='carrier'?4:1),0)<16){this.broodTimer=6;this.broods++;for(const side of [-1,1]){const x=matron.x+side*60,y=matron.y;this.pending.push({type:'crawler',x,y,elite:false,delay:850});this.emit({type:'enemy-warning',x,y,radius:32,durationMs:850});}}}}
  for(let i=this.pending.length-1;i>=0;i--){const p=this.pending[i];p.delay-=ms;if(p.delay>0)continue;if(this.spawn(p.type,p.x,p.y,p.elite,p.guardian))this.pending.splice(i,1);else if((p.attempts=(p.attempts??0)+1)>40){const point=this.geometry.breaches[p.attempts%this.geometry.breaches.length];p.x=point.x+(point.facing==='east'?56:-56);p.y=point.y;}}
  this.encounterEvents(this.director.update(ms,this.enemies.activeCount+this.enemies.reservedCount+this.pending.reduce((n,p)=>n+(p.type==='carrier'?4:1),0)));if(this.clearRequested){this.clearRequested=false;this.clearRoom();}
 }
}
