import {hasClearExpeditionShot} from './game/world/expeditionGeometry';
import {enemyShotRadius} from './game/combat/enemyContact';
import type {DepthGame,GameInput} from './DepthGame';
import type {DepthRenderer} from './render/DepthRenderer';
const WEAPONS=['pistol','rifle','shotgun','plasma','rocket'] as const;
/** Each thumb owns its pointer. Auxiliary actions never release the move pointer. */
export class InputController {
 private keys=new Set<string>();private moveId:number|null=null;private fireId:number|null=null;private moveOrigin={x:0,y:0};private fireOrigin={x:0,y:0};private movement={x:0,y:0};private aim:number|null=null;private mouse={x:0,y:0,active:false};private shooting=false;private touchFire=false;
 constructor(private game:DepthGame,private view:DepthRenderer,private onPause:(toggle?:boolean)=>void){
  const zone=document.querySelector<HTMLElement>('#move-zone')!,stick=document.querySelector<HTMLElement>('#stick')!,knob=document.querySelector<HTMLElement>('#knob')!,fire=document.querySelector<HTMLElement>('#fire')!;
  zone.addEventListener('pointerdown',e=>{if(this.game.status!=='playing'||this.moveId!==null)return;e.preventDefault();this.moveId=e.pointerId;this.moveOrigin={x:e.clientX,y:e.clientY};zone.setPointerCapture(e.pointerId);stick.style.left=`${e.clientX}px`;stick.style.top=`${e.clientY}px`;stick.classList.add('active');});
  zone.addEventListener('pointermove',e=>{if(e.pointerId!==this.moveId)return;const x=e.clientX-this.moveOrigin.x,y=e.clientY-this.moveOrigin.y,d=Math.max(48,Math.hypot(x,y));this.movement={x:x/d,y:y/d};knob.style.transform=`translate(${x/d*42}px,${y/d*42}px)`;});
  const releaseMove=(e:PointerEvent)=>{if(e.pointerId!==this.moveId)return;this.moveId=null;this.movement={x:0,y:0};stick.classList.remove('active');knob.style.transform='';};['pointerup','pointercancel','lostpointercapture'].forEach(t=>zone.addEventListener(t,releaseMove as EventListener));
  fire.addEventListener('pointerdown',e=>{if(this.game.status!=='playing'||this.fireId!==null)return;e.preventDefault();this.fireId=e.pointerId;this.fireOrigin={x:e.clientX,y:e.clientY};this.touchFire=true;this.aim=null;fire.setPointerCapture(e.pointerId);fire.classList.add('held');});
  fire.addEventListener('pointermove',e=>{if(e.pointerId!==this.fireId)return;const dx=e.clientX-this.fireOrigin.x,dy=e.clientY-this.fireOrigin.y;this.aim=Math.hypot(dx,dy)>20?Math.atan2(dy/.81,dx):null;});
  const releaseFire=(e:PointerEvent)=>{if(e.pointerId!==this.fireId)return;this.fireId=null;this.touchFire=false;this.aim=null;fire.classList.remove('held');};['pointerup','pointercancel','lostpointercapture'].forEach(t=>fire.addEventListener(t,releaseFire as EventListener));
  const canvas=view.canvas;canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse')this.mouse={x:e.clientX,y:e.clientY,active:true};});canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0||game.status!=='playing')return;this.shooting=true;this.mouse={x:e.clientX,y:e.clientY,active:true};canvas.setPointerCapture(e.pointerId);});['pointerup','pointercancel','lostpointercapture'].forEach(t=>canvas.addEventListener(t,()=>{this.shooting=false;}));
  document.addEventListener('keydown',e=>{if((e.target as HTMLElement).matches('input,select'))return;const key=e.key.toLowerCase();if(game.status==='playing'&&[' ','arrowup','arrowdown','arrowleft','arrowright'].includes(key))e.preventDefault();this.keys.add(key);if(e.repeat)return;if(key==='escape'){this.onPause(true);return;}if(game.status!=='playing')return;if(key==='r')game.reload();if(key==='g')game.grenade();if(key==='e')game.heal();if('12345'.includes(key))game.switchWeapon(WEAPONS[Number(key)-1]);});document.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));
  for(const [id,action]of [['reload',()=>game.reload()],['grenade',()=>game.grenade()],['heal',()=>game.heal()]] as const){document.getElementById(id)!.addEventListener('pointerdown',e=>{e.preventDefault();action();});}
  window.addEventListener('blur',()=>{this.reset();this.onPause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.reset();this.onPause();}});window.addEventListener('resize',()=>this.reset());document.addEventListener('contextmenu',e=>e.preventDefault());
 }
 reset(){this.keys.clear();this.movement={x:0,y:0};this.moveId=this.fireId=null;this.shooting=this.touchFire=false;this.aim=null;document.querySelector('#stick')?.classList.remove('active');document.querySelector('#fire')?.classList.remove('held');const knob=document.querySelector<HTMLElement>('#knob');if(knob)knob.style.transform='';}
 read():GameInput{const k=this.keys;let x=this.movement.x+(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0),y=this.movement.y+(k.has('s')||k.has('arrowdown')?1:0)-(k.has('w')||k.has('arrowup')?1:0);y/=.81;let angle=this.aim;if(!this.touchFire&&!k.has(' ')&&this.mouse.active){const point=this.view.pointer(this.mouse.x,this.mouse.y,this.game.targets().filter(t=>hasClearExpeditionShot(this.game.geometry,this.game.player,t)).map(t=>{const e=t.id>0?this.game.enemies.getSnapshot(t.id):undefined;return {...t,radius:e?enemyShotRadius(e.type,e.elite):t.radius};}));if(point)angle=Math.atan2(point.y-this.game.player.y,point.x-this.game.player.x);}return{x,y,angle,autoAim:this.touchFire||k.has(' '),fire:this.touchFire||this.shooting||k.has(' ')};}
}
