import { describe, expect, it, vi } from 'vitest';
import { EffectsSystem } from '../../src/game/effects/EffectsSystem';
import { DeathVisualView } from '../../src/game/effects/DeathVisualView';

class FakeImage {
  active=true; visible=true; texture=''; frame: number|undefined; x=0; y=0; tint?:number; alpha=1; scaleX=1; scaleY=1; rotation=0; flipX=false; flipY=false; depth=0;
  setTexture(v:string, f?:number){this.texture=v;this.frame=f;return this} setFrame(v:number){this.frame=v;return this}
  setPosition(x:number,y:number){this.x=x;this.y=y;return this} setTint(v:number){this.tint=v;return this} clearTint(){this.tint=undefined;return this}
  setAlpha(v:number){this.alpha=v;return this} setScale(x:number,y=x){this.scaleX=x;this.scaleY=y;return this} setRotation(v:number){this.rotation=v;return this}
  setFlip(x:boolean,y:boolean){this.flipX=x;this.flipY=y;return this} setDepth(v:number){this.depth=v;return this} setActive(v:boolean){this.active=v;return this} setVisible(v:boolean){this.visible=v;return this}
}
const setup=(loaded=true, limits?:{blood:number;corpse:number}, onEffectsChanged=()=>{})=>{const images:FakeImage[]=[]; const effects=new EffectsSystem('high'); const view=new DeathVisualView({effects,hasTexture:(k)=>loaded && (k==='skin-crawler'||k==='blood-decals'),createImage:()=>{const i=new FakeImage();images.push(i);return i as never},poolLimits:limits,onEffectsChanged}); return {images,effects,view}};

describe('DeathVisualView',()=>{
 it('admits one blood decal and corpse with family assets and deterministic static variation',()=>{const {view,effects}=setup(); expect(view.spawnDeath({family:'crawler',x:10,y:20})).toBe(true); expect(effects.count('decals')).toBe(1);expect(effects.count('remains')).toBe(1); const s=view.snapshot; expect(s.blood[0]).toMatchObject({texture:'blood-decals'});expect(s.corpses[0]).toMatchObject({texture:'skin-crawler',frame:6}); expect(s.blood[0]?.rotation).toBe(view.snapshot.blood[0]?.rotation)});
 it('uses frameless tinted fallbacks and rejects invalid coordinates without records',()=>{const {view,effects}=setup(false);expect(view.spawnDeath({family:'spitter',x:1,y:2})).toBe(true);expect(view.snapshot.blood[0]).toMatchObject({frame:undefined,tint:0xd8d94a});expect(view.spawnDeath({family:'crawler',x:NaN,y:2})).toBe(false);expect(effects.count('remains')).toBe(1)});
 it('rotates paired death visuals after saturation without dropping accepted deaths',()=>{const {view,images,effects}=setup();const accepted:number[]=[];for(let i=0;i<1000;i++){expect(view.spawnDeath({family:i%2===0?'crawler':'spitter',x:i,y:i})).toBe(true);accepted.push(effects.snapshot('remains').at(-1)!.id)}const remains=effects.snapshot('remains');expect(remains).toHaveLength(32);expect(remains.at(-1)?.id).toBe(accepted.at(-1));expect(remains.some(({id})=>id===accepted[0])).toBe(false);expect(view.snapshot.corpses).toHaveLength(32);expect(view.snapshot.corpses.at(-1)).toMatchObject({family:'spitter',x:999,y:999});expect(view.snapshot.blood).toHaveLength(128);expect(images.length).toBeLessThanOrEqual(160);expect(view.snapshot.corpseAllocated).toBeLessThanOrEqual(32);expect(view.snapshot.bloodAllocated).toBeLessThanOrEqual(128);effects.setProfile('low');view.syncRetainedIds();expect(view.snapshot.corpses.length).toBe(8);expect(view.snapshot.blood.length).toBe(32)});
 it('fully resets reused slots and keeps queen composition blood-only',()=>{const {view,effects}=setup(false);view.spawnDeath({family:'spitter',x:1,y:2,elite:true,rotation:2}); const ids=effects.snapshot('remains').map(x=>x.id);effects.remove(ids[0]!);view.syncRetainedIds();view.spawnQueenBlood({x:3,y:4,major:true});expect(effects.count('remains')).toBe(0);expect(effects.snapshot('decals').filter(({label})=>label==='blood-queen')).toHaveLength(1);expect(view.snapshot.blood.at(-1)).toMatchObject({family:'queen',x:3,y:4});view.clear(true);expect(view.snapshot.blood).toHaveLength(0);expect(view.snapshot.corpses).toHaveLength(0)});
 it('drops bookkeeping without mutating displays at shutdown',()=>{const {view,images}=setup();view.spawnDeath({family:'crawler',x:1,y:2});view.clear(false);expect(images.every(i=>i.active)).toBe(true);expect(view.snapshot.corpses).toHaveLength(0)});
 it('rejects paired admission atomically when saturated remains are protected',()=>{const changed=vi.fn();const {view,effects}=setup(true,undefined,changed);for(let i=0;i<effects.limits.remains;i++)effects.add('remains',{label:`protected-${i}`,essential:true});const beforeDecals=effects.snapshot('decals');const beforeRemains=effects.snapshot('remains');expect(view.spawnDeath({family:'crawler',x:1,y:2})).toBe(false);expect(effects.snapshot('decals')).toEqual(beforeDecals);expect(effects.snapshot('remains')).toEqual(beforeRemains);expect(view.snapshot).toMatchObject({bloodAllocated:0,corpseAllocated:0,blood:[],corpses:[]});expect(changed).not.toHaveBeenCalled()});
 it('preflights visual capacity before committing logical records',()=>{const {view,effects}=setup(true,{blood:1,corpse:1});expect(view.spawnDeath({family:'crawler',x:1,y:1,major:true})).toBe(true);const beforeDecals=effects.snapshot('decals');const beforeRemains=effects.snapshot('remains');expect(view.spawnDeath({family:'queen',x:2,y:2,major:true})).toBe(false);expect(effects.snapshot('decals')).toEqual(beforeDecals);expect(effects.snapshot('remains')).toEqual(beforeRemains);expect(view.snapshot.corpses).toHaveLength(1)});
 it('retires only projected generic records at logical caps and preserves all others',()=>{const {view,effects}=setup();for(let i=0;i<effects.limits.decals;i++)effects.add('decals',{label:`generic-decal-${i}`});for(let i=0;i<effects.limits.remains;i++)effects.add('remains',{label:`generic-remains-${i}`});const decals=effects.snapshot('decals');const remains=effects.snapshot('remains');expect(view.spawnDeath({family:'crawler',x:4,y:5})).toBe(true);expect(effects.snapshot('decals').filter(({id})=>decals.some(x=>x.id===id))).toEqual(decals.slice(1));expect(effects.snapshot('remains').filter(({id})=>remains.some(x=>x.id===id))).toEqual(remains.slice(1));expect(effects.count('decals')).toBe(effects.limits.decals);expect(effects.count('remains')).toBe(effects.limits.remains)});
 it('notifies shared display reconciliation after admissions and retirement changes',()=>{const changed=vi.fn();const {view,effects}=setup(true,undefined,changed);view.spawnDeath({family:'crawler',x:1,y:2});expect(changed).toHaveBeenCalledTimes(1);effects.setProfile('low');view.syncRetainedIds();expect(changed).toHaveBeenCalledTimes(2)});
});
